### ISSUE TITLE
纯js的app.vue如何注入啊，是还不支持的吗

### ISSUE THREAD

**Issue by saikete** [Murphy-Tong/page-stack-vue3#2]

**Comment by Murphy-Tong** [comment]
什么意思？CDN？

**Comment by saikete** [comment]
不是，我看项目是用app.tsx写入的，我的项目是app.vue，所以写法上有点不大一致，有些纳闷，需要我改入口文件吗？readme文件写是在view-router文件里注入，是指router.js文件吗。。。

**Comment by Murphy-Tong** [comment]
<template>
  <router-view v-slot="{ Component, route }">
    <PageStack :router="router">
      <component :is="Component" :key="route.path" />
    </PageStack>
  </router-view>
</template>

import PageStack from "page-stack-vue3";

**Comment by Murphy-Tong** [comment]
```
<template>
  <router-view v-slot="{ Component, route }">
    <PageStack :router="router">
      <component :is="Component" :key="route.path" />
    </PageStack>
  </router-view>
</template>
import PageStack from "page-stack-vue3";
const router = useRouter();
```

**Comment by saikete** [comment]
经测试页面重复跳转的时候会有报错，第一次跳转保存了，但是第二次开始就没有了，使用浏览器前进后退的时候会有queryselectAll报错，需要写个demo复现吗

**Comment by Murphy-Tong** [comment]
在codepen上写一个吧

**Comment by saikete** [comment]
无法完美复现项目中的问题，但是逻辑和使用嵌套路由一致无法实现
https://github.com/saikete/h5-anime/tree/feature

项目中代码报错如下：
![image](https://user-images.githubusercontent.com/45237450/230551346-6d34924b-6237-45b2-b159-b838ed72abe3.png)
这个问题是在back()第二次页面时出现（重复跳转两次

![image](https://user-images.githubusercontent.com/45237450/230551564-cb8b39a5-1ea3-49d4-9346-4e731ab6e640.png)
这个问题是在浏览器前进后退页面栈中出现

比较和单页面路由时无此问题初步判断可能是嵌套路由导致的，复现地址中无此报错，但无法实现缓存页面

**Comment by Murphy-Tong** [comment]
应该是嵌套路由响应了路由变化重新渲染了页面。在嵌套路由里面加一个keep-alive试试

**Comment by saikete** [comment]
经测试直接包裹一层keepAlive标签也不大行

**Comment by saikete** [comment]
配合keepAlive已实现app页面栈效果，期望star越来越多
