### ISSUE TITLE
加载组件之后切换路由页面重复调用两次

### ISSUE THREAD

**Issue by saikete** [Murphy-Tong/page-stack-vue3#3]
如题，导致created接口请求走了两遍

![image](https://user-images.githubusercontent.com/45237450/230593341-d43b0a7e-5881-4223-9bca-fbc83663119d.png)

**Comment by Murphy-Tong** [comment]
1.把这个组件换成keep-alive ，看看还会不会出现问题，如果出现了，说明不是这个组件的问题。
2.如果换成keep-alive没有出现问题，需要提供一下复现步骤或者demo

**Comment by saikete** [comment]
![image](https://user-images.githubusercontent.com/45237450/231038541-7eee4c70-fc47-4e40-9601-d1f41cb5e9f5.png)
不是插件的问题，App.vue内使用KeepAlive问题仍然存在，删除KeepAlive问题即消失，问题是否出现在KeepAlive上？

**Comment by Murphy-Tong** [comment]
那么你可以检查一下，是不是你自己的代码逻辑本身就有问题，比如动态的组件key。一般来说官方组件不会有什么问题，或者你可以提供一个能复现bug的demo看看
