### ISSUE TITLE
不能缓存多级路由？

### ISSUE THREAD

**Issue by 178me** [Murphy-Tong/page-stack-vue3#4]
经过测试使用，发现目前应该只能缓存到一级路由，
在多极路由的情况下缓存会失效，
我的临时解决方案是在二级以上的router-view里面套一层KeepAlive，但是这样子会有一些其他的问题，比如说，同级路由之间他不会保留元素状态(滚动条),
不知道大佬有没有什么好办法？

**Comment by Murphy-Tong** [comment]
提供一下所使用的的组件版本号以及复现demo。
